Rayserve
aws-samples/awsome-inference pull request #11
Opened 2024-08-05 18:10 UTC by mvinci12

*Issue #, if available:*

*Description of changes:*
added rayserve examples

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-05 21:51 UTC, amanshanbhag commented on 2.projects/.DS_Store
This looks like a metadata dump file. Is this required? If yes, why is it under 2.projects?

2024-08-05 21:52 UTC, amanshanbhag commented on 2.projects/ray-service/.DS_Store
Same here. Is this file required?

2024-08-05 21:57 UTC, amanshanbhag commented on 2.projects/ray-service/README.md
We've deleted the "Acknowledgement" section from all READMEs. Please delete from here too

2024-08-05 21:59 UTC, amanshanbhag requested changes
Couple of comments on files. Once fixed, this should be good to go!

2024-08-05 22:06 UTC, amanshanbhag commented on 2.projects/ray-service/README.md
Please make sure the EKS cluster has been setup, either from a given example in [infrastructure](https://github.com/aws-samples/awsome-inference/blob/rayserve/2.projects/ray-service/infrastructure)

Typo

2024-08-05 22:07 UTC, amanshanbhag commented on 2.projects/ray-service/README.md
"Note: In both of these examples, you have the option to edit the RayService yaml file. This can include adjusting the number of worker pods, adjusting the resource requirements of your pods, mounting any volumes, adding tolerations to your worker pods, etc. And overall, these yaml files can be used as a template for inference on other models as well."

Please add the name(s) of template file explicitly

2024-08-05 22:09 UTC, amanshanbhag commented on 2.projects/ray-service/StableDiffusion/stable_diffusion.py.zip
Why is there a zip file here?

2024-08-05 22:09 UTC, amanshanbhag commented on 2.projects/ray-service/StableDiffusion/output.png
Is this output file required?

2024-08-06 16:00 UTC, mvinci12 commented on 2.projects/.DS_Store
yeah not needed

2024-08-06 16:01 UTC, mvinci12 commented on 2.projects/ray-service/.DS_Store
nope

2024-08-06 16:01 UTC, mvinci12 commented on 2.projects/ray-service/README.md
will do

2024-08-06 18:06 UTC, amanshanbhag approved these changes
LGTM! Merging

2024-08-06 18:08 UTC, merged