Mixture of Agents
aws-samples/awsome-inference pull request #28
Opened 2024-10-11 18:50 UTC by EashanKaushik

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-17 19:00 UTC, amanshanbhag requested changes
This is great stuff! Just a few small changes, and I'll merge! Thanks Eashan

2024-10-17 19:00 UTC, amanshanbhag commented on .DS_Store
Delete this file please

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/.DS_Store
Delete this file please

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/README.md
Can you add architecture diagram image too? The link currently points to nothing

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/alpaca_eval/README.md
I assume this file is required as part of the OS License? If so, at the top, can you please add a sentence in:
- What is AlpacaEval (your own definition)
- How it's being used
- "Below is the readme provided by the AlpacaEval team [here](link)"

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/README.md
Can you also add a section in here for benchmarking/evaluation? At a high level:
- Describe the process
- Say where readers can find results

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/alpaca_eval/results/claude-3-5-sonnet-20240620/model_outputs.json
Is this file necessary for the repo?

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/alpaca_eval/results/claude-3-5-sonnet-20240620/model_outputs.json
If yes, please also add a quick description of what the file is somewhere (ideally on the readme that you have for MoA)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/alpaca_eval/results/gpt4_1106_preview/model_outputs.json
Is this file necessary for the repo? If yes, please also add a quick description of what the file is somewhere (ideally on the readme that you have for MoA)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/architecture-advanced.png
I see the AD here! Make sure the link is right in the README!

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/outputs/anthropic.claude-3-haiku-20240307-v1_0-moa-extended-eval-set-round-11.json
Is this file necessary for the repo? If yes, please also add a quick description of what the file is somewhere (ideally on the readme that you have for MoA)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/outputs/anthropic.claude-3-haiku-20240307-v1_0-moa-round-11.json
Is this file necessary for the repo? If yes, please also add a quick description of what the file is somewhere (ideally on the readme that you have for MoA)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/mixture-of-agents.ipynb
Please commit a clean version of the notebook (i.e., without the outputs)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/mixture-of-agents.ipynb
Can you also add text blocks in there? For example, explain what the functions definitions are, explain the usage section etc. If someone new to this is reading your notebook for the first time, they should be able to tell what code block they're about to run without really reading through the code (or at least get a high level idea of it from the description)

2024-10-17 19:00 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/mixture-of-agents.ipynb
Can you also write a quick para for why you choose specific models for reference and/or aggregator? Also add in the link to the score webpage you showed me!

2024-10-19 17:13 UTC, EashanKaushik commented on 2.projects/mixture-of-agents/README.md
Architecture diagram is in the readme right ?

2024-10-21 16:29 UTC, EashanKaushik commented on 2.projects/mixture-of-agents/mixture-of-agents.ipynb
Hi cleared most of the outputs, but few cells show output. I think it adds value, as these cells show what output of a function looks like.

2024-10-21 16:32 UTC, amanshanbhag commented on 2.projects/mixture-of-agents/README.md
Yes! When I was doing the review, the AD in the readme didn't resolve (it just showed the alt). I assume it's linked wrongly, since AD is present in the directory

2024-10-21 16:51 UTC, EashanKaushik commented on 2.projects/mixture-of-agents/README.md
Is it showing now?

2024-10-21 16:55 UTC, amanshanbhag approved these changes
Thanks! LGTM

2024-10-21 16:55 UTC, merged